name: Build and Push n8n ARMv7 Image

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # ---------------------------
      # 1. Checkout repo
      # ---------------------------
      - name: Checkout repository
        uses: actions/checkout@v4

      # ---------------------------
      # 2. Free up disk space
      # ---------------------------
      - name: Free up disk space
        run: |
          echo "Before cleanup:"
          df -h
          sudo rm -rf /usr/share/dotnet /opt/ghc /usr/local/lib/android
          docker system prune -af
          echo "After cleanup:"
          df -h

      # ---------------------------
      # 3. Set up QEMU for ARM emulation
      # ---------------------------
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # ---------------------------
      # 4. Set up Docker Buildx (for multi-arch builds)
      # ---------------------------
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      # ---------------------------
      # 5. Login to GitHub Container Registry
      # ---------------------------
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # ---------------------------
      # 6. Build and Push with Cache
      # ---------------------------
      - name: Build and Push n8n ARMv7
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/arm/v7
          tags: ghcr.io/${{ github.repository_owner }}/n8n:armv7
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false
